# Generated by Django 6.1 on 2026-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_descripcion_alter_tarea_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', verbose_name='Descripción'),
        ),
    ]
